[package]
name = "rs2"
version = "0.1.0"
authors = ["Kyle Simpson <kyleandrew.simpson@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
env_logger = "0.7"
log = "0.4"

[dependencies.rs2_macro]
path = "./rs2_macro"